// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var CartridgeHeader$Yobml = require("../CartridgeHeader.bs.js");

function CartridgeInfoComponent(Props) {
  var cartridge = Props.cartridge;
  var header = cartridge[/* header */0];
  return React.createElement("ul", undefined, React.createElement("li", undefined, "Title: (TODO)"), React.createElement("li", undefined, "Mapper: " + CartridgeHeader$Yobml.mapper_to_string(header)), React.createElement("li", undefined, "ROM Size: " + (String(header[/* rom_size */1]) + " bytes")));
}

var make = CartridgeInfoComponent;

exports.make = make;
/* react Not a pure module */
