// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function get_cartridge_type(n) {
  switch (n) {
    case 0 : 
        return /* RomOnly */0;
    case 1 : 
    case 2 : 
    case 3 : 
        return /* MBC1 */1;
    case 4 : 
    case 6 : 
    case 7 : 
        return Pervasives.failwith("Unknown cartridge type");
    case 5 : 
    case 8 : 
    case 9 : 
        return /* MBC2 */2;
    default:
      return Pervasives.failwith("Unknown cartridge type");
  }
}

function get_rom_size(n) {
  return (32768 << n);
}

function get_ram_size(n) {
  switch (n) {
    case 0 : 
        return 0;
    case 1 : 
        return 2048;
    case 2 : 
        return 8192;
    case 3 : 
        return 32768;
    case 4 : 
        return 131072;
    default:
      return Pervasives.failwith("Unhandled ram size");
  }
}

function make(rom) {
  return /* record */[
          /* cartridge_type */get_cartridge_type(Caml_array.caml_array_get(rom, 327)),
          /* rom_size */(32768 << Caml_array.caml_array_get(rom, 328)),
          /* ram_size */get_ram_size(Caml_array.caml_array_get(rom, 329))
        ];
}

exports.get_cartridge_type = get_cartridge_type;
exports.get_rom_size = get_rom_size;
exports.get_ram_size = get_ram_size;
exports.make = make;
/* No side effect */
