// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ConsoleComponent$Yobml = require("./components/ConsoleComponent.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ConsoleComponent$Yobml.make, { }), "console");

/*  Not a pure module */
