// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function button_to_bit(button) {
  switch (button) {
    case 3 : 
    case 4 : 
        return 2;
    case 2 : 
    case 5 : 
        return 1;
    case 0 : 
    case 6 : 
        return 8;
    case 1 : 
    case 7 : 
        return 4;
    
  }
}

function make(param) {
  return /* record */[
          /* dpad */15,
          /* buttons */15,
          /* selector */192
        ];
}

function key_down(input, key) {
  if (key >= 4) {
    input[/* dpad */0] = input[/* dpad */0] & Pervasives.lnot(button_to_bit(key));
    return /* () */0;
  } else {
    input[/* buttons */1] = input[/* buttons */1] & Pervasives.lnot(button_to_bit(key));
    return /* () */0;
  }
}

function key_up(input, key) {
  if (key >= 4) {
    input[/* dpad */0] = input[/* dpad */0] | button_to_bit(key);
  } else {
    input[/* buttons */1] = input[/* buttons */1] | button_to_bit(key);
  }
  return /* () */0;
}

function get(input) {
  if ((input[/* selector */2] & 16) > 0) {
    return input[/* dpad */0] | input[/* selector */2];
  } else if ((input[/* selector */2] & 32) > 0) {
    return input[/* buttons */1] | input[/* selector */2];
  } else {
    return input[/* selector */2];
  }
}

function set(input, value) {
  input[/* selector */2] = value | 192;
  return /* () */0;
}

exports.button_to_bit = button_to_bit;
exports.make = make;
exports.key_down = key_down;
exports.key_up = key_up;
exports.get = get;
exports.set = set;
/* No side effect */
