// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Console$Yobml = require("./Console.bs.js");

var $$console = Console$Yobml.make(/* () */0);

Console$Yobml.run($$console);

exports.$$console = $$console;
/* console Not a pure module */
