// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var Memory$Yobml = require("./Memory.bs.js");
var Console$Yobml = require("./Console.bs.js");

var file = Fs.readFileSync("./roms/Dr. Mario (World).gb", "binary");

var rom = $$Array.mapi((function (n, param) {
        return Caml_string.get(file, n);
      }), Caml_array.caml_make_vect(file.length, 0));

var $$console = Console$Yobml.make(rom);

Curry._1(Printf.printf(/* Format */[
          /* Int */Block.__(4, [
              /* Int_X */8,
              /* Lit_padding */Block.__(0, [
                  /* Zeros */2,
                  2
                ]),
              /* No_precision */0,
              /* End_of_format */0
            ]),
          "%02X"
        ]), Memory$Yobml.load($$console[/* memory */2], 32755));

Console$Yobml.run($$console);

exports.file = file;
exports.rom = rom;
exports.$$console = $$console;
/* file Not a pure module */
